{-
-- Project Euler
-- https://projecteuler.net/

Triangular, pentagonal, and hexagonal
  Show HTML problem content  
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
-}

import qualified Data.Set as Set

-- Build the three sets up to 10^6
tri :: Set.Set Integer
tri = Set.fromList [t|n<- [1..10^6], let t = n*(n+1)`div`2]

pent :: Set.Set Integer
pent = Set.fromList [p|n<- [1..10^6], let p = n*(3*n-1)`div`2]

hex :: Set.Set Integer
hex = Set.fromList [h|n<- [1..10^6], let h = n*(2*n-1)]

-- Intersect the three sets 
-- tph -> fromList [1,40755,1533776805]
-- (3.82 secs, 1,422,281,296 bytes)
tph :: Set.Set Integer
tph = (tri `Set.intersection` pent) `Set.intersection` hex

-- Extract the last item of tph 
answer :: Integer
answer = (last.Set.toList) tph

--  main -> 1533776805
-- (4.69 secs, 1,422,266,984 bytes)
main :: IO ()
main = do  
    putStrLn$show answer

-- Congratulations, the answer you gave to problem 45 is correct.

-- You are the 69257th person to have solved this problem.


